config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "event#index"
  post 'seed_data', to: 'event#seed_data'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :events
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = where(nil)
      filtering_params.each do |key, value|
        p value
        results = results.public_send("filter_by_#{key}", value) if value.present?
      end
      results
    end
  end
end

app/models/data_source.rb
# == Schema Information
#
# Table name: data_sources
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class DataSource < ApplicationRecord
  has_many :events
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :bigint           not null, primary key
#  description    :text
#  end_date       :date
#  image_url      :string
#  start_date     :date
#  title          :string
#  url            :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  category_id    :bigint
#  data_source_id :bigint
#  location_id    :bigint
#
# Indexes
#
#  index_events_on_category_id     (category_id)
#  index_events_on_data_source_id  (data_source_id)
#  index_events_on_location_id     (location_id)
#
class Event < ApplicationRecord
  # Includes
  include Filterable

  #Scopes
  scope :filter_by_title, ->(title) { where('title like ?', "%#{sanitize_sql_like(title)}%") }
  scope :filter_by_category, ->(category) { where(category: Category.where('title like ?', "%#{sanitize_sql_like(category)}%")) }
  scope :filter_by_location, ->(location) { where(location: Location.where('title like ?', "%#{sanitize_sql_like(location)}%")) }
  scope :filter_by_data_source, ->(data_source) { where(data_source: DataSource.where('title like ?', "%#{sanitize_sql_like(data_source)}%")) }
  scope :filter_by_start_date, ->(start_date) { where(start_date: start_date..) }
  scope :filter_by_end_date, ->(end_date) { where(end_date: ..end_date) }

  # Relationship
  belongs_to :data_source
  belongs_to :category
  belongs_to :location

  # Make url as slug to not repat any data
  validates :url, presence: true, uniqueness: true

  def full_dates
    "#{start_date&.strftime('%F')} - #{end_date&.strftime('%F')}"
  end
  def self.actives_dependency
    # underscore for attributes
    [Location, Category, DataSource]
  end
  def self.seed_json_data
    json_file = File.join(Rails.root, 'db', 'seeds_json', 'export_data.json')
    Scrap.start unless File.readable?(json_file)
    data = JSON.parse(File.read(json_file))
    data['data'].each do |event_data|
      event = new(title: event_data['title'], image_url: event_data['image_url'],
                  url: event_data['url'], description: event_data['description'],
                  start_date: event_data['start_date'], end_date: event_data['end_date'])
      actives_dependency.each do |dependency|
        # to add for or Associate like Location Category DataSource
        value = dependency.find_or_create_by(title: event_data["#{dependency.to_s.underscore}"])
        event.send("#{dependency.to_s.underscore}=", value)
      end
      event.save
    end
  end
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Location < ApplicationRecord
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
    @pagy, @events = pagy(Event.filter(filtering_params))
  end

  def seed_data
    Event.seed_json_data
  end


  private

  def filtering_params
    params.slice(:title, :location, :start_date, :end_date, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Backend
  include Pagy::Frontend
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/event/_events.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% events.each do |event|  %>
        <div class="col">
          <div class="card shadow-sm">
            <img src=<%=event.image_url %> , class="bd-placeholder-img card-img-top"  width="100%" height="225">

            <div class="card-body">
              <h1 class="fw-light"> <%= event.title %></h1>

              <p class="card-text">
                <strong>Dates:</strong> <%=event.full_dates %>
              </p>
              <p class="card-text">
                <strong>Category:</strong> <%=event.category.title %>
              </p>
              <p class="card-text">
                <strong>Location:</strong> <%=event.location.title %>
              </p>
              <p class="card-text">
                <strong>DataSource:</strong> <%=event.data_source.title %>
              </p>



              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted"> <%=time_ago_in_words(event.created_at) %></small>
                <a href="<%= event.url %>" class="btn btn-primary">Book Now</a>

              </div>
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/event/_header.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Welcome to Events Engine</h1>
      <p class="lead text-muted">you can filter with Calendars in Berlin . (Should Handle JobBackgorund Later)</p>
      <%= form_tag(seed_data_path, method: 'post') do %>
        <%= submit_tag "Seed updated Data from Data source", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</section>

app/views/event/index.html.erb
<%= render "header" %>

<%= form_tag(root_path, method: 'get') do %>
  <%= text_field_tag(:title, params[:title] , class: "form-control" , placeholder: "Need search by title") %>
  <%= text_field_tag(:category, params[:category] , class: "form-control", placeholder: "Need search by category") %>
  <%= text_field_tag(:location, params[:location] , class: "form-control", placeholder: "Need search by Location") %>
<!--  <div class="container">-->
<!--    <div class="row">-->
<!--      <div class="col-sm">-->
<!--        <p>From</p>-->
        <%#= date_field(:start_date, params[:start_date]&.first , class: "form-control" ) %>
<!--      </div>-->
<!--      <div class="col-sm">-->
<!--        <p>To</p>-->
        <%#= date_field(:end_date, params[:end_date]&.first, class: "form-control" ) %>
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
  <%= submit_tag "Search", class: "btn btn-secondary" %>
<% end %>


<%= render "events" , events: @events %>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/layouts/_nav.html.erb
<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">Events</span>
    </a>

    <ul class="nav nav-pills">
      <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link">About</a></li>
    </ul>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BerlinCalendar</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render "layouts/nav" %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>